BookXchangeBE/Models/ConnectedMember.cs
namespace BookXchangeBE.Models
{
    public class ConnectedMember : Membre
    {
        public string Token { get; set; }

    }
}

BookXchangeBE/Models/ErrorViewModel.cs
namespace BookXchangeBE.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BookXchangeBE/Models/Livre.cs
namespace BookXchangeBE.Models
{
    public class Livre
    {
        public int IdLivre { get; set; }
        public string Titre { get; set; }

        public string Auteur { get; set; }

        public string Synopsis { get; set; }

    }
}

BookXchangeBE/Models/Mappers/LivreMapper.cs
using BookXchangeBE.BLL.DTO;

namespace BookXchangeBE.Models.Mappers
{
    internal static class LivreMapper
    {
        public static Livre ToModel(this LivreDTO dto)
        {
            return new Livre()
            {
                IdLivre = dto.IdLivre,
                Titre = dto.Titre,
                Auteur = dto.Auteur,
                Synopsis = dto.Synopsis,
            };
        }

        public static LivreDTO ToDTO(this Livre livre)
        {
            return new LivreDTO()
            {
                IdLivre = livre.IdLivre,
                Titre = livre.Titre,
                Auteur = livre.Auteur,
                Synopsis = livre.Synopsis,
            };
        }

    }
}

BookXchangeBE/Models/Mappers/MembreMapper.cs
using BookXchangeBE.BLL.DTO;

namespace BookXchangeBE.Models.Mappers
{
    internal static class MembreMapper
    {
        public static Membre ToModel(this MembreDTO dto)
        {
            return new Membre()
            {
                IdMembre = dto.IdMembre,
                Pseudo = dto.Pseudo,
                Email = dto.Email,
                Prenom = dto.Prenom,
                Nom = dto.Nom,
                Role = dto.Role
            };
        }
    }
}

BookXchangeBE/Models/Membre.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BookXchangeBE.Models
{
    public class Membre
    {
        public int IdMembre { get; set; }

        [DisplayName("Pseudo")]
        public string Pseudo { get; set; }

        [DisplayName("E-Mail")]
        public string Email { get; set; }

        [DisplayName("Prénom")]
        public string? Prenom { get; set; }

        [DisplayName("Nom")]
        public string? Nom { get; set; }

        [DisplayName("Role")]
        public int Role { get; set; }

        [DisplayName("Image")]
        public IFormFile? File { get; set; }

    }

    public class MembreRegister
    {
        [DisplayName("Pseudo")]
        [Required]
        public string Pseudo { get; set; }

        [DisplayName("E-Mail")]
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [DisplayName("Mot de passe")]
        [Required]
        [DataType(DataType.Password)]
        [RegularExpression(@"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$")]
        // Regle de la regex => Le mot de passe doit faire 8 caracteres, une miniscule, une majuscule et un chiffre
        public string Password { get; set; }

        [DisplayName("Confirmation")]
        [Required]
        [DataType(DataType.Password)]
        [Compare(nameof(Password))]
        public string PasswordConfirm { get; set; }

        [DisplayName("Role")]
        public int Role { get; set; }

    }

    public class MembreLogin
    {
        [DisplayName("Pseudo")]
        [Required]
        public string Pseudo { get; set; }

        [DisplayName("Mot de passe")]
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

    }
}

BookXchangeBE/Controllers/BookListController.cs
using BookXchangeBE.BLL.Services;
using BookXchangeBE.Models;
using BookXchangeBE.Models.Mappers;
using Microsoft.AspNetCore.Mvc;

namespace BookXchangeBE.Controllers
{
    public class BookListController : Controller
    {
        private LivreService livreService;

        public BookListController(LivreService livreService)
        {
            this.livreService = livreService;
        }

        public IActionResult Index()
        {
            IEnumerable<Livre> livres = livreService.GetAll()
                .Select(b => b.ToModel())
                .OrderBy(b => b.Titre);

            return View(livres);
        }
    }
}

BookXchangeBE/Controllers/HomeController.cs
using BookXchangeBE.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BookXchangeBE.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookXchangeBE/Controllers/MembreController.cs
using BookXchangeBE.BLL.Services;
using BookXchangeBE.Models;
using BookXchangeBE.Models.Mappers;
using Microsoft.AspNetCore.Mvc;

namespace BookXchangeBE.Controllers
{
    public class MembreController : Controller
    {

        private MembreService membreService;

        public MembreController(MembreService membreService)
        {
            this.membreService = membreService;
        }

        public IActionResult MemberList()
        {
            IEnumerable<Membre> membres = membreService.GetAll()
                .Select(b => b.ToModel())
                .OrderBy(b => b.Pseudo);

            return View(membres);
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register([FromForm] MembreRegister membreRegister)
        {
            if (!ModelState.IsValid)
            {
                return View(membreRegister);
            }

            // Check if Member exists
            if (membreService.CheckMemberExists(membreRegister.Pseudo, membreRegister.Email))
            {
                ModelState.AddModelError("", "Le compte existe déjà.");
                return View(membreRegister);
            }


            // Save Member in DB
            Membre membre = membreService.Insert(
                membreRegister.Pseudo,
                membreRegister.Email,
                membreRegister.Password,
                membreRegister.Role
            ).ToModel();

            // TODO Store Member in Session
            Console.WriteLine($"Member create with id {membre.IdMembre}");

            return RedirectToAction("Index", "Home");
        }


        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login([FromForm] MembreLogin membreLogin)
        {
            if (!ModelState.IsValid)
            {
                return View(membreLogin);
            }


            // Validation du hashage du mot de passe
            if (!membreService.CheckCredentials(membreLogin.Pseudo, membreLogin.Password))
            {
                ModelState.AddModelError("", "Les credentials ne sont pas valide");
                return View(membreLogin);
            }

            // Récuperation du compte via son pseudo
            Membre membre = membreService.GetByPseudo(membreLogin.Pseudo).ToModel();

            // TODO Store Member in Session
            Console.WriteLine($"Member login with id {membre.IdMembre}");



            return RedirectToAction("Index", "Home");
        }
        public IActionResult Logout()
        {
            return View();
        }

    }
}

BookXchangeBE/Views/BookList/Index.cshtml
@model IEnumerable<BookXchangeBE.Models.Livre>

@{
    ViewData["Title"] = "Liste de livres";
}

<h1>Liste de livres</h1>


<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdLivre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Auteur)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Synopsis)
            </th>
            <th>
                Details
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdLivre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Auteur)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Synopsis)
            </td>

            <td>
                <a class ="text-primary " asp-controller="BookList" asp-action="Details" asp-route-id ="@item.IdLivre" >
                    <i class="bi bi-search"> go to details </i>
                </a>
            </td>
                                    
        </tr>
}
    </tbody>
</table>

BookXchangeBE/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BookXchangeBE/Views/Membre/Login.cshtml
@model BookXchangeBE.Models.MembreLogin

@{
    ViewData["Title"] = "Login";
}

<h1>S'identifier</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Pseudo" class="control-label"></label>
                <input asp-for="Pseudo" class="form-control" />
                <span asp-validation-for="Pseudo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookXchangeBE/Views/Membre/MemberList.cshtml
@model IEnumerable<BookXchangeBE.Models.Membre>

@{
    ViewData["Title"] = "Liste de membres";
}

<h1>Liste de membres</h1>


<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdMembre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pseudo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Role)
            </th>
            <th>
                Details
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdMembre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pseudo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Role)
            </td>

            <td>
                <a class ="text-primary " asp-controller="Member" asp-action="GetMember" asp-route-id ="@item.IdMembre" >
                    <i class="bi bi-search"> go to details </i>
                </a>
            </td>
                                    
        </tr>
}
    </tbody>
</table>

BookXchangeBE/Views/Membre/Register.cshtml
@model BookXchangeBE.Models.MembreRegister

@{
    ViewData["Title"] = "Register";
}

<h1>S'inscrire</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Pseudo" class="control-label"></label>
                <input asp-for="Pseudo" class="form-control" />
                <span asp-validation-for="Pseudo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PasswordConfirm" class="control-label"></label>
                <input asp-for="PasswordConfirm" class="form-control" />
                <span asp-validation-for="PasswordConfirm" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control" />
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookXchangeBE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookXchangeBE</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookXchangeBE.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookXchangeBE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BookList" asp-action="Index">Liste de livres</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Membre" asp-action="MemberList">Liste des membres</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Membre" asp-action="Login">S'identifier</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Membre" asp-action="Register">S'inscrire</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BookXchangeBE - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>